include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = CassowaryKit
LIBRARY_NAME = CassowaryKit

CassowaryKit_HEADER_FILES = \
CSWConstraint.h \
CSWConstraintFactory.h \
CSWConstraintOperator.h \
CSWEditInfo.h \
CSWEditVariableManager.h \
CSWEpsilon.h \
CSWFloatComparator.h \
CSWLinearExpression.h \
CSWSimplexSolver.h \
CSWSimplexSolver+PrivateMethods.h \
CSWStrength.h \
CSWTierWeightedStrength.h \
CSWSuggestion.h \
CSWSymbolicWeight.h \
CSWTableau.h \
CSWVariable.h \
CSWTracableSimplexSolver.h \
CSWTestObject.h \
CSWTableauConstraintConverter.h \
CSWSimplexSolverSolution.h

CassowaryKit_OBJC_FILES = \
CSWConstraint.m \
CSWConstraintFactory.m \
CSWEditInfo.m \
CSWEditVariableManager.m \
CSWFloatComparator.m \
CSWLinearExpression.m \
CSWSimplexSolver.m \
CSWStrength.m \
CSWTierWeightedStrength.m \
CSWSuggestion.m \
CSWSymbolicWeight.m \
CSWTableau.m \
CSWTracableSimplexSolver.m \
CSWVariable.m \
CSWTableauConstraintConverter.m \
CSWSimplexSolverSolution.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/library.make
-include GNUmakefile.postamble